name: Benoît Lévêque
markdown: redcarpet
pygments: true
baseurl: http://benoitleveque.fr
comments:
    disqus:
        short_name: benoitlvque
analytics:
    id: UA-40716275-1
    name: benoitleveque.fr
